<?php
/**
 * TL_ROOT/system/modules/tags_news/languages/ja/modules.php 
 * 
 * Contao extension: tags_news 1.3.0 stable 
 * Japanese translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['FMD']['tagcloudnews']['0'] = "タグクラウド(ニュース)";
$GLOBALS['TL_LANG']['FMD']['tagcloudnews']['1'] = "このモジュールはニュースの項目用のタグクラウドを表示します。";
 
?>
