<?php
/**
 * TL_ROOT/system/modules/tags_news/languages/de/modules.php 
 * 
 * TYPOlight extension: tags_news 1.1.1 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['FMD']['tagcloudnews']['0'] = "Tag Cloud (Nachrichten)";
$GLOBALS['TL_LANG']['FMD']['tagcloudnews']['1'] = "Dieses Modul zeigt eine Liste mit Auszeichnungen (Tag Cloud) für Nachrichtenbeiträge an.";
 
?>
