<?php
/**
 * TL_ROOT/system/modules/tags_news/languages/de/tl_module.php 
 * 
 * TYPOlight extension: tags_news 1.1.1 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['tag_news_archives']['0'] = "Einschränkung auf Nachrichtenarchive";
$GLOBALS['TL_LANG']['tl_module']['tag_news_archives']['1'] = "Wählen Sie bitte die Nachrichtenarchive aus, deren Auszeichnungen für die Tag Cloud verwendet werden sollen.";
 
?>
